spring:
    datasource:
        url: jdbc:mysql://localhost:12001/host_brd?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                ddl-auto: update
    mail: 
        host: smtp.gmail.com
        port: 587
        username: smpp99999@gmail.com
        password: ichmzfzkiyfxfbhg
        properties: 
            mail: 
                smtp: 
                    auth: true
                starttls: 
                    enable: true

# App Properties
app:
    jwtSecret:  this-is-very-very-secret
    jwtExpirationMs: 86400000

logging:
    level:
        root: ERROR
        org.springframework.web: ERROR
        org.springframework.security: TRACE    
        org.hibernate: ERROR    

