server:
    port: 9091


spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/HtiSmsDB
        username: springuser
        password: ThePassword
        driver-class-name: com.mysql.jdbc.Driver


