server:
  port: 9090
  ssl:
    key-alias: spring-https
    key-store: classpath:smpp.jks
    key-store-type: JKS
    key-password: smpp6263
    key-store-password: smpp6263
    trust-store: classpath:smpp.jks
    trust-store-type: JKS
    trust-store-password: smpp6263

spring:
  application:
    name: API-GATEWAY-SERVICE

eureka:
  instance:
    hostname: API-GATEWAY-SERVICE
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
