server:
  port: 9090

spring:
  application:
    name: API-GATEWAY-SERVICE


eureka:
  instance:
    hostname: API-GATEWAY-SERVICE
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
