server:
    port: 8082

spring: 
  application:
    name: personal-service

eureka:
  instance:
    hostname: personal-service
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka